name: Python application

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]
        poetry-version: ["1.8.2"]

    services:
      postgres:
        image: postgres:13.0-alpine
        env:
          POSTGRES_USER: bookstore_dev
          POSTGRES_PASSWORD: bookstore_dev
          POSTGRES_DB: bookstore_dev_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set working directory to repository root
      run: pwd
      working-directory: .

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install poetry ${{ matrix.poetry-version }}
      run: |
        pipx install poetry==${{ matrix.poetry-version }}

    - name: Install dependencies (root folder)
      working-directory: .
      run: poetry install

    - name: Run tests
      working-directory: .
      env:
        SQL_DATABASE: bookstore_dev_db
        SQL_USER: bookstore_dev
        SQL_PASSWORD: bookstore_dev
        SQL_HOST: localhost
        SQL_PORT: 5432
      run: |
        poetry run python manage.py test
