name: Python application

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.12]

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:16.0-alpine
        ports:
          - 5434:5432
        env:
          POSTGRES_USER: bookstore_dev
          POSTGRES_PASSWORD: bookstore_dev
          POSTGRES_DB: bookstore_dev_db

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Install poetry
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip
          python -m pip install --upgrade poetry

      - name: Install dependencies
        working-directory: ./
        run: poetry install

      - name: Start Docker Compose services
        working-directory: ./
        run: docker-compose up -d --build

      - name: Run Tests
        working-directory: ./
        run: docker-compose exec -T web python manage.py test